#define BYTE_NULO 0x00

// BYTE_MOVER 0x10
#define MOVER_IZQUIERDA 0x01
#define MOVER_DERECHA 0x02
#define APUNTAR_ARRIBA 0x03
#define SALTAR_ALETEAR 0x04
#define CAER 0x05

// BYTE_INTERACTUAR 0x20
#define DISPARAR 0x11
#define TIRAR_PISO 0x12
#define TOMAR_ARMA 0X13
#define RECARGAR 0x14

// DIRECCIONES
#define DIRECCION_IZQUIERDA 0x01
#define DIRECCION_DERECHA 0x02
#define DIRECCION_ARRIBA 0x03

// ARMAS
#define GRANADA 0x01
#define BANANA 0x02
#define PEW_PEW_LASER 0x03
#define LASER_RIFLE 0x04
#define AK_47 0x05
#define PISTOLA_DE_DUELOS 0x06
#define PISTOLA_COWBOY 0x07
#define MAGNUM 0x08
#define ESCOPETA 0x09
#define SNIPER 0x0A

//ACCIONES
#define ESTADO_MOVIMIENTO "MOVIMIENTO"
#define ESTADO_SALTO "SALTO"
#define ESTADO_DIRECCION "DIRECCION"
#define ESTADO_PISO "PISO"
#define ESTADO_ARMA "ARMA"
#define ESTADO_BALAS "BALAS"
#define ESTADO_ARMADURA "ARMADURA"
#define ESTADO_CASCO "CASCO"













#define MAPA_CAJAS 0x02
#define MAPA_TILES 0x03
#define MAPA_SPAWNS 0x04
#define MAPA_EQUIPAMIENTO 0x05
#define ARMADURA "armadura"
#define ARMA "arma"
#define CASCO "casco"  
#define BYTE_ARMADURA 0X06
#define BYTE_CASCO 0X07
#define BYTE_ARMA 0X08









