#define BYTE_NULO 0x00

// BYTE_MOVER 0x10
#define MOVER_IZQUIERDA 0x01
#define DEJAR_MOVER_IZQUIERDA 0x10
#define MOVER_DERECHA 0x02
#define DEJAR_MOVER_DERECHA 0x20
#define APUNTAR_ARRIBA 0x03
#define DEJAR_APUNTAR_ARRIBA 0x30
#define SALTAR_ALETEAR 0x04
#define DEJAR_SALTAR_ALETEAR 0x40
#define CAER 0x05

// BYTE_INTERACTUAR 0x20
#define DISPARAR 0x11
#define TIRAR_PISO 0x12
#define DEJAR_TIRAR_PISO 0x21
#define TOMAR_ARMA 0X13
#define SOLTAR_ARMA 0x31

// DIRECCIONES
#define DIRECCION_IZQUIERDA 0x01
#define DIRECCION_DERECHA 0x02
#define DIRECCION_ARRIBA 0x03

// ARMAS
#define GRANADA 0x01
#define BANANA 0x02
#define PEW_PEW_LASER 0x03
#define LASER_RIFLE 0x04
#define AK_47 0x05
#define PISTOLA_DE_DUELOS 0x06
#define PISTOLA_COWBOY 0x07
#define MAGNUM 0x08
#define ESCOPETA 0x09
#define SNIPER 0x0A

//ACCIONES
#define ESTADO_MOVIMIENTO "MOVIMIENTO"
#define ESTADO_SALTO "SALTO"
#define ESTADO_DIRECCION "DIRECCION"
#define ESTADO_PISO "PISO"
#define ESTADO_ARMA "ARMA"
#define ESTADO_BALAS "BALAS"
#define ESTADO_ARMADURA "ARMADURA"
#define ESTADO_CASCO "CASCO"
#define ESTADO_MUNICION "MUNICION"
#define ESTADO_POS_X_FINAL_BALA "POS_X_FINAL_BALA"

// TECLAS
#define DERECHA "d"
#define IZQUIERDA "a"
#define ARRIBA "w"
#define ABAJO "s"
#define SALTO " "
#define DISPARO "f"
#define AGARRAR_ARMA "g"

#define NO_DERECHA "!d"
#define NO_IZQUIERDA "!a"
#define NO_ARRIBA "!w"
#define NO_ABAJO "!s"
#define NO_SALTO "! "
#define NO_DISPARO "!f"
#define NO_AGARRAR_ARMA "!g"

// PIXELES
#define PIXEL_PATO 32
#define PIXEL_BALA 64
#define PIXEL_ARMA 32













#define MAPA_CAJAS 0x02
#define MAPA_TILES 0x03
#define MAPA_SPAWNS 0x04
#define MAPA_EQUIPAMIENTO 0x05
#define ARMADURA "armadura"
#define ARMA "arma"
#define CASCO "casco"  
#define BYTE_ARMADURA 0X06
#define BYTE_CASCO 0X07
#define BYTE_ARMA 0X08









